import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'] , weight: "500"})

export const metadata: Metadata = {
  title: 'Imagelite App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`white-text ${roboto.className}`}>{children}</body>
    </html>
  )
}
